---
root: true

extends:
  - airbnb-base
  - plugin:import/errors

env:
    node: true
    browser: true
    es6: true

parser: babel-eslint

rules:
  no-console: off
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  template-curly-spacing:
    - error
    - always
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides:
        return: { after: true }
        throw: { after: true }
        case: { after: true }
  